services:
  backend:
    image: bkrajendra/blooddonation-backend:latest
    container_name: backend
    # pull_policy: always
    volumes:
      - ./data:/app/data
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=3000
    # networks:
    #   - app-network

  frontend:
    image: bkrajendra/blooddonation-frontend:latest
    container_name: frontend
    # pull_policy: always
    volumes:
      - ./assets/config.json:/usr/share/nginx/html/assets/config.json
    restart: always
    depends_on:
      - backend
    # networks:
    #   - app-network

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    # networks:
    #   - app-network
     
# networks:
#   app-network:
#     driver: bridge